<a href="https://colab.research.google.com/github/Evidence11710/Evi-links-/blob/main/Iris_Regression_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris

import pandas as pd

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
X = df[['sepal length (cm)', 'sepal width (cm)', 'petal width (cm)']]

y = df['petal length (cm)']

X.head()

   sepal length (cm)  sepal width (cm)  petal width (cm)
0                5.1               3.5               0.2
1                4.9               3.0               0.2
2                4.7               3.2               0.2
3                4.6               3.1               0.2
4                5.0               3.6               0.2

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X, y, test_size=0.2, random_state=42

)

print("Training data:", X_train.shape)

print("Testing data:", X_test.shape)

Training data: (120, 3)
Testing data: (30, 3)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully

In [ ]:
y_pred = model.predict(X_test)

results = pd.DataFrame({

    'Actual Petal Length': y_test.values,

    'Predicted Petal Length': y_pred

})

results.head(10)

   Actual Petal Length  Predicted Petal Length
0                  4.7                4.127716
1                  1.7                1.882002
2                  6.9                7.025659
3                  4.5                4.432110
4                  4.8                4.927191
5                  1.5                2.066237
6                  3.6                3.849479
7                  5.1                6.129499
8                  4.5                5.021745
9                  3.9                3.974453

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)

print("Mean Squared Error:", mse)

print("R2 Score:", r2)

Mean Absolute Error: 0.2605179846252388
Mean Squared Error: 0.13001626031382701
R2 Score: 0.9603293155857663

In [ ]:
results['Error'] = results['Actual Petal Length'] - results['Predicted Petal Length']

print(results.head(10))

print("\nConclusion:")

print("The Linear Regression model successfully predicted the petal length.")

print("The error shows the difference between the actual and predicted values.")

print("Smaller error values indicate better predictions.")

   Actual Petal Length  Predicted Petal Length     Error
0                  4.7                4.127716  0.572284
1                  1.7                1.882002 -0.182002
2                  6.9                7.025659 -0.125659
3                  4.5                4.432110  0.067890
4                  4.8                4.927191 -0.127191
5                  1.5                2.066237 -0.566237
6                  3.6                3.849479 -0.249479
7                  5.1                6.129499 -1.029499
8                  4.5                5.021745 -0.521745
9                  3.9                3.974453 -0.074453

Conclusion:
The Linear Regression model successfully predicted the petal length.
The error shows the difference between the actual and predicted values.
Smaller error values indicate better predictions.